### ISSUE TITLE
Difference between -f1 and -f2 file input options

### ISSUE THREAD

**Issue by shadiakiki1986** [BorgwardtLab/GLIDE#1]
Hello. What is the difference between -f1 and -f2 file input options? I have a single nsamples x nsnps matrix for the genotype, of values 0/1/2. Should this matrix be divided into 2 parts and passed to GLIDE in `-f1` and `-f2`?

**Comment by tkamth** [comment]
hi @shadiakiki1986,  the idea is that you would need to partition your genotype file into small blocks which is dependent on the memory of your GPU, and perform all possible combinations between and within them.  In our instance, we partitioned it into 2k variants and ran all combinations using the `-f1` and `-f2` specification.  

Hope this makes sense to you.

**Comment by shadiakiki1986** [comment]
thanks
